# Generated by Django 3.1.7 on 2021-04-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MorobeAdministrationDrivingPermit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_id', models.CharField(max_length=20)),
                ('madp_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('division', models.CharField(choices=[('PAO', "PA'S OFFICE"), ('MTR', 'MOTOTR TRAFFIC REGISTRY'), ('LFS', 'LAE FIRE STATION')], max_length=255)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('Exp', 'Expired'), ('Val', 'Valid'), ('Sup', 'Suspended')], max_length=20)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('officer', models.CharField(max_length=20)),
            ],
        ),
    ]
