# Generated by Django 3.1.7 on 2021-04-08 17:54

from django.db import migrations, models
import pl.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_id', models.CharField(default=pl.models.generate_lid, max_length=15)),
                ('db_id', models.CharField(default=pl.models.generate_db_id, max_length=20)),
                ('surname', models.CharField(max_length=50)),
                ('given_names', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Female', 'F'), ('Male', 'M')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('nationality', models.CharField(choices=[('Citizen', 'Papua New Guinean'), ('Non-citizen', 'Expatriate')], max_length=20)),
                ('class_of_licence', models.CharField(choices=[('1', 'One (1)'), ('2', 'Two (2)'), ('3', 'Three (3)'), ('4', 'Four (4)'), ('5', 'Five (5)'), ('6', 'Six (6)'), ('7', 'Seven (7)')], max_length=20)),
                ('validity', models.DecimalField(decimal_places=0, max_digits=3)),
                ('date_issued', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('SUS', 'Suspended'), ('CND', 'Cancelled'), ('VLD', 'Valid'), ('EXP', 'Expired')], max_length=20)),
                ('old_licence_number', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
