# Generated by Django 3.1.7 on 2021-04-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='licence_type',
            field=models.CharField(choices=[('PNG-DL', "PNG Driver's Licence"), ('PNG-PDL', 'Provisional Licence')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
