# Generated by Django 3.1.7 on 2021-04-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_id', models.CharField(max_length=50)),
                ('reg_id', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('postal_address', models.CharField(max_length=255)),
                ('residential_address', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('engine_capacity', models.DecimalField(decimal_places=0, max_digits=6)),
                ('engine_no', models.CharField(max_length=50)),
                ('chassis_no', models.CharField(max_length=50)),
                ('uProv', models.CharField(max_length=50)),
                ('UComm', models.CharField(max_length=50)),
                ('tare_weight', models.DecimalField(decimal_places=0, max_digits=7)),
                ('maximum_load', models.DecimalField(decimal_places=0, max_digits=7)),
                ('officer', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
