# Generated by Django 3.1.7 on 2021-04-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='vehicle_image',
            field=models.CharField(default=0, max_length=2058),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='UComm',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='maximum_load',
            field=models.DecimalField(decimal_places=0, help_text='Weight to the nearest kilogram (kg)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='registration',
            name='tare_weight',
            field=models.DecimalField(decimal_places=0, help_text='Weight to the nearest kilogram (kg)', max_digits=7),
        ),
    ]
