# Generated by Django 3.1.7 on 2021-04-16 09:36

from django.db import migrations, models
import vr.models


class Migration(migrations.Migration):

    dependencies = [
        ('vr', '0002_auto_20210416_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='db_id',
            field=models.CharField(default=vr.models.generate_db_id, max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reg_id',
            field=models.CharField(default=vr.models.generate_id, max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='uProv',
            field=models.CharField(choices=[('MBE', 'Morobe'), ('MDG', 'Madang'), ('EHP', 'Eastern Highlands'), ('NCD', 'National Capital District')], max_length=50),
        ),
    ]
