# Generated by Django 3.1.7 on 2021-04-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PmvLicence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_id', models.CharField(max_length=20)),
                ('pmv_licence_id', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=20)),
                ('place_of_birth', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('postal_address', models.CharField(max_length=255)),
                ('residential', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('mileage', models.DecimalField(decimal_places=0, max_digits=10)),
                ('maximum_passenger', models.DecimalField(decimal_places=0, max_digits=4)),
                ('authorized_route', models.CharField(choices=[('R1', 'Route 1'), ('R2', 'Route 2'), ('R3', 'Route 3'), ('R100', 'Route 100')], max_length=20)),
                ('other_routes', models.CharField(choices=[('17A', 'Market-Town-Malahang'), ('11C', 'Market-Town-Taraka'), ('14B', 'Town-Eriku-4 Mile')], max_length=20)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('officer', models.CharField(max_length=20)),
            ],
        ),
    ]
