# Generated by Django 3.1.7 on 2021-04-07 13:19

from django.db import migrations, models
import dlearn.models


class Migration(migrations.Migration):

    dependencies = [
        ('dlearn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerspermit',
            name='age',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learnerspermit',
            name='complexion',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learnerspermit',
            name='eyes',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learnerspermit',
            name='height',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learnerspermit',
            name='db_id',
            field=models.CharField(default=dlearn.models.generate_db_id, max_length=20),
        ),
    ]
