# Generated by Django 3.1.7 on 2021-04-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlearn', '0002_auto_20210407_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerspermit',
            name='officer_id',
            field=models.CharField(choices=[('Officer - Admin', 'OAD'), ('Officer-Licencing', 'OLC'), ('Officer - Technical', 'OTC'), ('Superintendent', 'SPT'), ('Officer - TIN', 'OTN')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learnerspermit',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
